version: '3.3'

services:

  ui:
    restart: "no"
    volumes:
      - ${PROJECT_PATH}/daveweb-ui:/usr/src/app
    ports:
      - "8026:4200"
    links:
      - api
    entrypoint:
      - ng
      - serve
      - --host
      - "0.0.0.0"
      - --disable-host-check
      - --aot
      - --build-optimizer
      - --environment=dev

  api:
    restart: "no"
    volumes:
      - ${PROJECT_PATH}/daveweb-api:/usr/src/app
    ports:
      - "8025:8025"
    environment:
      - DEBUG=True
    entrypoint:
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8025
