version: '3.3'

services:

  ui:
    restart: on-failure
    build: ./daveweb-ui
    env_file: .env
    volumes:
      - ui_dist:/dist

  api:
    restart: always
    build: ./daveweb-api
    env_file: .env
    links:
      - db
    volumes:
      - api_static:/srv/static
      - api_media:/srv/media

  db:
    restart: always
    image: postgres:alpine
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:

  ui_dist: {}

  db_data: {}

  api_static: {}

  api_media: {}
